### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by julmedvedeva** [citizenweb3/validatorinfo#109]
- The overall look is very different. The elements layout, especially the top block that contains the header (which right now isnt in the header), the search panel and the buttons are not in place.  #104 
- The main table is missing a lot of elements, and a few more examples (more validator rows + some icons next to validator name would give a different feel) 
- The icons are missing
- The empty pages are missing the 404 text and robot
- The left menu does not do what its intended to do (https://github.com/citizenweb3/validatorinfo/issues/57)
- Image links, such as bottom menu are missing (it shows 3 citizenweb3 links)
- Its missing altogether the right login icon (in figma its the picture under the top right menu) - its parallel to the left v.info logo 
- filters and other elements are still missing

**Comment by serejandmyself** [comment]
Irrelevant until Alpha
