### ISSUE TITLE
Mobile version design

### ISSUE THREAD

**Issue by serejandmyself** [citizenweb3/validatorinfo#129]
- Tablet
- iPAD
- Android
- Iphone

- main table: remove tvs, links, assets, battery image
- only icons throughout the site
- no web3 login initially
- no val nodes visual
- no game
-

**Comment by serejandmyself** [comment]
1) main page: change SS, TS, etc to: Tech. Social Gov. User
2) reward calculator. shorten text to:

**Comment by sasarte** [comment]
To take the Profile button ok reward calculator like we did on the main desing?

**Comment by serejandmyself** [comment]
initial work done

**Comment by sasarte** [comment]
1) main page: missing customize filter ON behavior 
- comapre validator: add yearly to filter. mayby on mobile somethign like "Timescale:" (opens submenu with daiy, weekly, monthly, yearly (applicble for all charts and pages) OR
- on mobile, everywhere we have a choise of menus, like: timescale, or ecosysrems, etc - we call all the same "customize" and it will have same behavior, just different objects insdie
- add text to the box that pops out when you press the left menu filter (3 lines):
After the menu: 
"Anon, please note that my mobile version has limited features. To enjoy all of my perks, and to login into your account, please visit my desktop version" (link on dekstop version)
- ad calendar to calculations after all =)
- error page

2) validator profile, top part: remove visual. Add top name: "Citizen Web3: Details", when click on expand on detyails, you have description, all links, podcast player. then the medals
- network table: state, network name, apr, fans, V.P., comms
- public goods: remove submit option. 
- governance sumamry: remove val created props

3) val on X top: just the logo of network and validator
- val passport: vanity cahrt remove, remove auth z perms
- val tx overview AND val rich list: remove block height 

4) network profile, top: same as with valdiator then: "Namada, Details". After expand details, we have: descritpion, links AND labels + show TXs button. 
- network passport: remove chart
- in statistics remove buttom part of operator distribution chart
- governace, remove visual of live proposals. leave liek this:
"Live Proposals: 
- #234 PROP NAME (will have link to the prop details page)
- dev indo: remove pre vote and pre commit info
- peers, seeds, binary version should open small boxes with info?
- remove developer activity 
- in token: remove price chart

5) tx info:
- tx summary of network page: remove block height
