### ISSUE TITLE
Search icon appears when typing

### ISSUE THREAD

**Issue by serejandmyself** [citizenweb3/validatorinfo#143]
- The app contains a search field
- In rest state, it shows a magnifying glass
- When a user types letters and then hovers off, the magnifying glass still remains - thats a bug

**Comment by chinmay3012** [comment]
I have identified the cause of the issue where the search icon remains visible after typing. The problem can be resolved by updating the CSS to hide the icon when input is detected.

.search-icon {
  display: inline-block;
}

input:focus + .search-icon,
input:not(:placeholder-shown) + .search-icon {
  display: none;
}

This change ensures the icon disappears once the user starts typing. Please review and let me know if any further adjustments are needed.

**Comment by serejandmyself** [comment]
https://dev.validatorinfo.com/

**Comment by chinmay3012** [comment]
Are you satisfied with the solution provided ?

**Comment by serejandmyself** [comment]
> Are you satisfied with the solution provided ?

Hey man. Our apologies for not getting back sooner. My fault.

AFAIK, the fix that was actually used, was different. I believe by @stribulsergey 

Still, thank you for the solution, and hopefully will note your messages quicker. Sorry again

**Comment by chinmay3012** [comment]
Thanks man for your valuable feedback.
Actually I am new to this open source contribution field, so learning along the way .

**Comment by serejandmyself** [comment]
> Thanks man for your valuable feedback. Actually I am new to this open source contribution field, so learning along the way .

I would say you did a great job, more our miss =(

We're learning too =)
