### ISSUE TITLE
Main left menu design

### ISSUE THREAD

**Issue by serejandmyself** [citizenweb3/validatorinfo#32]
- Visual though every page
- Stays the same
- Whenever a user is on page X it should be highlighted by the menu 
- Menu hovers left and back with button - need button design and hover design
- Menu: Validators, Networks, Metrics, Library, Staking Calculator, Validator Comparison, About Us
- Each button should have an own symbol next to it

**Comment by serejandmyself** [comment]
Review comments for @sasarte:

1) Dont like the network icon at all, lets re-do it 
2) Validator icon - maybe make the V a bit more unique? But good one - i see a lot of other projects use that too
3) About us - not suitable here. It should be a house
4) Validator comparison: blue and red, not green and red

**Comment by sasarte** [comment]
@serejandmyself please check the changes made.
