### ISSUE TITLE
DEMO validatorinfo

### ISSUE THREAD

**Issue by serejandmyself** [citizenweb3/validatorinfo#55]
## Definition of done
- [x] Basic navigation/routing: issue #74 
- [ ] Static/reactive: buttons, other basic CSS elements should be reactive as described in tasks. Actual information, such as validator and network info, can be NaN. Elements that are ready can be implemented 
- [ ] Show cases the design of the following pages/elements: main page with tabs (including all designed elements); validator profile page with tabs and designed elements; about us page with tabs and designed elements; network profile page with tabs and designed elements; help page with tabs (virtually an empty page); top, side, bottom and other designed menus of the website;

**Comment by julmedvedeva** [comment]
i didn't understand)) which of item from Figma visuals i need use? i planned develop this page ([link to page](https://www.figma.com/file/kvfWG0oXnRu0zsJKMxvNa9/Untitled?type=design&node-id=4-171&mode=design&t=Hs10F7koiMieKB7S-4) ) 
but now I see new project with two UI ([link](https://www.figma.com/file/9a96KSn3xGivSWa6NA9Lzi/Validators.info?type=design&node-id=1-2&mode=design&t=eIjCCpx50L6BQOfC-4) )
what of this already done to developed?

**Comment by serejandmyself** [comment]
> i didn't understand)) which of item from Figma visuals i need use? i planned develop this page ([link to page](https://www.figma.com/file/kvfWG0oXnRu0zsJKMxvNa9/Untitled?type=design&node-id=4-171&mode=design&t=Hs10F7koiMieKB7S-4) ) but now I see new project with two UI ([link](https://www.figma.com/file/9a96KSn3xGivSWa6NA9Lzi/Validators.info?type=design&node-id=1-2&mode=design&t=eIjCCpx50L6BQOfC-4) ) what of this already done to developed?

You are looking at the right design. What has been done is what was shared during the call and whatever is in the feature/validator branch. 

The design is constantly being updated, as more detail and elements are added by @sasarte 

The second link seems to be outdated, Unsure where it popped up

**Comment by serejandmyself** [comment]
Closed in favor of Alpha release
